### ISSUE TITLE
Commercial extension

### ISSUE THREAD

**Issue by filerun** [madve2/uppp-pixabay-for-office#1]
Hi Dániel, interested in a paid project to build a very similar extension? E-mail me at *

**Comment by madve2** [comment]
Thanks for reaching out, I'm glad you found the extension this promising! I'm pretty occupied with other projects these days, so I'm afraid I can't build your extension – but absolutely feel free to fork this one, and let me know if you have any questions about how it works!

**Comment by filerun** [comment]
Thanks nevertheless!
